// Command pons is the client and server entry point for the pons runtime.
//
// Authentication: ANTHROPIC_API_KEY (provider anthropic, default) or
// OPENAI_API_KEY (provider openai, also works with any OpenAI-compatible
// server via -base-url, e.g. llama.cpp or Ollama). ChatGPT subscription
// codex auth comes from pons's own auth file via --login.
package main

import (
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"log"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"syscall"

	"github.com/samperrin/pons/plugins/brain/llm"
	"github.com/samperrin/pons/protocol"
)

func main() {
	logger := log.New(os.Stderr, "", log.LstdFlags)
	mode := "bundled"
	if len(os.Args) > 1 && (os.Args[1] == "serve" || os.Args[1] == "client") {
		mode = os.Args[1]
		os.Args = append([]string{os.Args[0]}, os.Args[2:]...)
	}

	// First Ctrl+C/SIGTERM cancels the current run (external plugin
	// children are shut down by their defers); a second signal kills.
	rootCtx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	provider := flag.String("provider", "anthropic", "LLM provider: anthropic | openai | codex | openai-responses")
	model := flag.String("model", "", "model id (default: provider default)")
	baseURL := flag.String("base-url", "", "override provider endpoint (for OpenAI-compatible servers)")
	workspace := flag.String("workspace", "", "workspace root the tools are jailed to (default: current directory)")
	stateDir := flag.String("state-dir", "", "runtime state directory (default: ~/.pons/runtime/<munged-project-path>/)")
	compactChars := flag.Int("compact-chars", 0, "conversation size (chars) before auto-compaction; 0 = default ~400k, negative = off")
	debug := flag.Bool("debug", false, "verbose: raw tool results, provider turn details")
	message := flag.String("message", "", "task to submit to the runtime")
	asAuth := flag.String("as", "", "codex login: store credentials under this auth id (default: codex)")
	login := flag.Bool("login", false, "codex only: authenticate with ChatGPT (browser flow), save credentials, and exit")
	maxTurns := flag.Int("max-turns", 12, "loop budget")
	// Tool output caps: everything the model can be handed back is bounded,
	// and every bound is tunable from the composition.
	fsReadBytes := flag.Int("fs-read-bytes", 0, "read_file byte cap; 0 = 256KiB default, negative = unlimited")
	bashTimeout := flag.Int("bash-timeout", 60, "default bash timeout seconds; 0 = no default timeout")
	bashMaxLines := flag.Int("bash-max-lines", 200, "bash output tail-truncation lines")
	bashMaxBytes := flag.Int("bash-max-bytes", 50*1024, "bash output byte cap")
	pluginMaxResultBytes := flag.Int("plugin-max-result-bytes", 0, "external plugin tool result byte cap; 0 = 1MiB default")
	var fallbackFlags repeatableStrings
	flag.Var(&fallbackFlags, "fallback", "fallback provider as provider or provider:model (repeatable; tried in order when the primary fails)")
	interactive := flag.Bool("i", false, "interactive runtime client: read tasks from stdin, one per line")
	pluginPath := flag.String("plugin-path", "", "PATH supplied to external plugin children (credentials are not inherited by default)")
	sandbox := flag.String("sandbox", "", `per-run execution environment: "seatbelt" (default: in-process)`)
	sandboxNetwork := flag.Bool("sandbox-network", false, "allow network access inside the per-run sandbox")
	handsCommand := flag.String("hands-command", "", "pons-hands executable used by the sandbox (default: find pons-hands on PATH)")
	runtimeAddress := flag.String("addr", "127.0.0.1:7337", "runtime server listen address (serve mode; loopback only)")
	serverURL := flag.String("server", "http://127.0.0.1:7337", "runtime server URL (client mode)")
	conversationID := flag.String("conversation", "", "existing runtime conversation id (client mode)")
	idempotencyKey := flag.String("idempotency-key", "", "stable message retry key (client mode; generated by default)")
	runtimeConcurrency := flag.Int("runtime-concurrency", 4, "maximum active agent runs (serve mode)")
	var pluginPaths repeatableStrings
	flag.Var(&pluginPaths, "plugin", "explicit external hands plugin manifest (repeatable; never discovered implicitly)")
	flag.Parse()

	if mode == "client" {
		if err := runClient(rootCtx, *serverURL, *conversationID, *idempotencyKey, *message, *interactive); err != nil && !errors.Is(err, context.Canceled) {
			logger.Printf("client: %v", err)
			os.Exit(1)
		}
		return
	}

	// Workspace: each server-managed run works on this directory.
	ws := *workspace
	if ws == "" {
		ws = "."
	}
	ws, err := filepath.Abs(ws)
	if err != nil {
		panic(err)
	}
	// Durable settings: ~/.pons/config.json (global) + .pons.json in the
	// workspace (project). Explicit flags always win over both.
	home, _ := os.UserHomeDir()
	cfg, err := loadSettings(home, ws)
	if err != nil {
		logger.Printf("%v", err)
		os.Exit(1)
	}
	setFlags := map[string]bool{}
	flag.Visit(func(f *flag.Flag) { setFlags[f.Name] = true })
	applyString := func(name string, dst *string, v *string) {
		if !setFlags[name] && v != nil {
			*dst = *v
		}
	}
	applyInt := func(name string, dst *int, v *int) {
		if !setFlags[name] && v != nil {
			*dst = *v
		}
	}
	applyString("provider", provider, cfg.Provider)
	applyString("model", model, cfg.Model)
	applyString("base-url", baseURL, cfg.BaseURL)
	applyString("state-dir", stateDir, cfg.StateDir)
	applyInt("max-turns", maxTurns, cfg.MaxTurns)
	applyInt("compact-chars", compactChars, cfg.CompactChars)
	applyInt("fs-read-bytes", fsReadBytes, cfg.FsReadBytes)
	applyInt("bash-timeout", bashTimeout, cfg.BashTimeout)
	applyInt("bash-max-lines", bashMaxLines, cfg.BashMaxLines)
	applyInt("bash-max-bytes", bashMaxBytes, cfg.BashMaxBytes)
	applyInt("plugin-max-result-bytes", pluginMaxResultBytes, cfg.PluginMaxResultBytes)

	// Provider failover chain: config providers + flags → ordered slots
	// (primary first, then failover entries).
	slots, serr := providerSlots(cfg, setFlags, *provider, *model, *baseURL, fallbackFlags)
	if serr != nil {
		logger.Printf("%v", serr)
		os.Exit(1)
	}
	primary, fallbacks := slots[0], slots[1:]

	brainLogger := logger
	if !*debug {
		brainLogger = nil // quiet: no provider chatter
	}
	if *asAuth != "" && !*login {
		logger.Printf("--as applies to --login")
		os.Exit(1)
	}
	if *login {
		if *provider != "codex" {
			logger.Printf("--login applies to the codex provider")
			os.Exit(1)
		}
		// Bare --login writes the singular "codex" entry; -as names a
		// specific subscription credential.
		if lerr := llm.RunLogin(context.Background(), *asAuth); lerr != nil {
			logger.Printf("login: %v", lerr)
			os.Exit(1)
		}
		return
	}

	brainConfig := llm.Config{
		Provider:     primary.Provider,
		Model:        primary.Model,
		BaseURL:      primary.BaseURL,
		APIKey:       primary.APIKey,
		Logger:       brainLogger,
		CompactChars: *compactChars,
		Fallbacks:    fallbacks,
	}

	if mode == "serve" && (*message != "" || *interactive) {
		logger.Printf("serve: --message and -i are client options")
		os.Exit(1)
	}
	statePath := *stateDir
	if statePath == "" {
		statePath = filepath.Join(home, ".pons", "runtime", strings.ReplaceAll(ws, "/", "-"))
	}
	logger.Printf("runtime state: %s", statePath)
	serverOpts := serverOptions{
		Address: *runtimeAddress, StateDir: statePath, Workspace: ws,
		MaxConcurrent: *runtimeConcurrency, MaxTurns: *maxTurns, Brain: brainConfig,
		FSReadBytes: *fsReadBytes, BashTimeout: *bashTimeout, BashMaxLines: *bashMaxLines, BashMaxBytes: *bashMaxBytes,
		PluginPaths: pluginPaths, PluginPath: *pluginPath, PluginMaxResultBytes: *pluginMaxResultBytes, Debug: *debug,
	}
	serverOpts.Environment, serverOpts.EnvironmentSpec, err = executionEnvironment(*sandbox, *handsCommand, *sandboxNetwork, serverOpts)
	if err != nil {
		logger.Printf("sandbox: %v", err)
		os.Exit(1)
	}
	if mode == "serve" {
		if err := runServer(rootCtx, logger, serverOpts); err != nil {
			logger.Printf("serve: %v", err)
			os.Exit(1)
		}
		return
	}
	bundledInteractive := *interactive || *message == ""
	if err := runBundled(rootCtx, logger, serverOpts, *conversationID, *idempotencyKey, *message, bundledInteractive); err != nil && !errors.Is(err, context.Canceled) {
		logger.Printf("run: %v", err)
		os.Exit(1)
	}
}

type repeatableStrings []string

func (r *repeatableStrings) String() string { return strings.Join(*r, ",") }

func (r *repeatableStrings) Set(value string) error {
	if strings.TrimSpace(value) == "" {
		return fmt.Errorf("plugin path must not be empty")
	}
	*r = append(*r, value)
	return nil
}

func isTTY(f *os.File) bool {
	info, err := f.Stat()
	if err != nil {
		return false
	}
	return info.Mode()&os.ModeCharDevice != 0
}

// primaryArg picks the human-meaningful argument of a tool call for the
// compact transcript line.
func primaryArg(a *protocol.Action) string {
	args, err := protocol.ObjectArgs(a.Args)
	if err != nil {
		return firstLine(string(a.Args), 100)
	}
	for _, key := range []string{"command", "path", "query"} {
		if v, ok := args[key]; ok {
			return firstLine(jsonValuePreview(v), 100)
		}
	}
	for _, v := range args {
		return firstLine(jsonValuePreview(v), 100)
	}
	return ""
}

func jsonValuePreview(raw json.RawMessage) string {
	var s string
	if err := json.Unmarshal(raw, &s); err == nil {
		return s
	}
	return string(raw)
}

func firstLine(s string, n int) string {
	s = strings.SplitN(s, "\n", 2)[0]
	if len(s) > n {
		s = s[:n] + "…"
	}
	return s
}

// showResult prints a tool result indented under its call, capped so a
// huge output doesn't drown the transcript; --debug shows everything.
func showResult(obs string) {
	if strings.TrimSpace(obs) == "" {
		fmt.Printf("  ⇢ (no output)\n")
		return
	}
	const maxLines, maxChars = 8, 480
	lines := strings.Split(strings.TrimRight(obs, "\n"), "\n")
	shown, used := 0, 0
	for _, l := range lines {
		if shown >= maxLines || used+len(l) > maxChars {
			fmt.Printf("  ⇢ … %d more line(s) — run with --debug for the full output\n", len(lines)-shown)
			return
		}
		fmt.Printf("  ⇢ %s\n", l)
		used += len(l)
		shown++
	}
}
