//go:build ignore

// gen_catalog writes catalog_gen.go: the wire API each model speaks, for
// presets whose models do not all share one API. Source: models.dev, the
// catalog OpenCode itself routes by. Run with `make catalog`.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"log"
	"maps"
	"net/http"
	"os"
	"slices"
	"time"
)

// presets maps a pons preset to its models.dev provider ID.
var presets = map[string]string{
	"opencode-go": "opencode-go",
}

// apis maps models.dev's AI SDK package names to pons wire APIs.
var apis = map[string]string{
	"@ai-sdk/anthropic":         "APIAnthropicMessages",
	"@ai-sdk/openai":            "APIOpenAIResponses",
	"@ai-sdk/openai-compatible": "APIOpenAICompletions",
}

type provider struct {
	NPM    string `json:"npm"`
	Models map[string]struct {
		Provider *struct {
			NPM string `json:"npm"`
		} `json:"provider"`
	} `json:"models"`
}

func main() {
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get("https://models.dev/api.json")
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		log.Fatalf("models.dev: %s", resp.Status)
	}
	var catalog map[string]provider
	if err := json.NewDecoder(resp.Body).Decode(&catalog); err != nil {
		log.Fatal(err)
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by gen_catalog.go from models.dev; DO NOT EDIT.\n\n")
	out.WriteString("package llm\n\n")
	out.WriteString("// catalog maps preset → model → wire API.\n")
	out.WriteString("var catalog = map[string]map[string]string{\n")
	for _, name := range slices.Sorted(maps.Keys(presets)) {
		p, ok := catalog[presets[name]]
		if !ok {
			log.Fatalf("models.dev has no provider %q", presets[name])
		}
		fmt.Fprintf(&out, "\t%q: {\n", name)
		for _, id := range slices.Sorted(maps.Keys(p.Models)) {
			npm := p.NPM
			if m := p.Models[id]; m.Provider != nil && m.Provider.NPM != "" {
				npm = m.Provider.NPM
			}
			api, ok := apis[npm]
			if !ok {
				log.Fatalf("%s/%s: no API for package %q", name, id, npm)
			}
			fmt.Fprintf(&out, "\t\t%q: %s,\n", id, api)
		}
		out.WriteString("\t},\n")
	}
	out.WriteString("}\n")

	src, err := format.Source(out.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("catalog_gen.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
}
